Fix clang-12 -Wimplicit-function-declaration warnings
`-std=gnu11` causes `#include <time.h>` to expose the `nanosleep()` function.

    hal/user_comps/mb2hal/mb2hal.c:166:17: error: implicit declaration of function 'nanosleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    nanosleep(ts);
                    ^
    hal/user_comps/mb2hal/mb2hal.c:182:17: error: implicit declaration of function 'usleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    usleep(1000);
                    ^
    hal/user_comps/mb2hal/mb2hal.c:182:17: note: did you mean 'sleep'?
    /usr/include/unistd.h:444:21: note: 'sleep' declared here
    extern unsigned int sleep (unsigned int __seconds);
                        ^
    hal/user_comps/mb2hal/mb2hal.c:249:17: error: implicit declaration of function 'usleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    usleep(this_mb_tx->cfg_serial_delay_ms * 1000);
                    ^
    hal/user_comps/mb2hal/mb2hal.c:256:17: error: implicit declaration of function 'usleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    usleep(gbl.slowdown * 1000 * 1000);
                    ^
    4 errors generated.
    make: *** [Makefile:378: objects/hal/user_comps/mb2hal/mb2hal.o] Error 1